name: vorzela_native_splash
description: Native Android/iOS splash generator with high-DPI assets and modern exit animations (YouTube/Gmail-style).
version: 0.0.7
homepage: https://github.com/vorzela/vorzela_native_splash
repository: https://github.com/vorzela/vorzela_native_splash
license: MIT

environment:
  sdk: ^3.3.0
  flutter: ">=3.16.0"

dependencies:
  flutter:
    sdk: flutter
  args: ^2.5.0
  image: ^4.3.0
  path: ^1.9.0
  yaml: ^3.1.2
  xml: ^6.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

executables:
  create: create
  remove: remove

flutter: null
