import 'dart:io';

import 'package:image/image.dart' as img;
import 'package:path/path.dart' as p;

import 'android_writer.dart';
import 'config.dart';
import 'dimensions.dart';
import 'ios_writer.dart';

class GenerateResult {
  GenerateResult(this.summary);
  final String summary;
}

class SplashGenerator {
  SplashGenerator({required this.root, required this.config});

  final String root;
  final SplashConfig config;

  Future<GenerateResult> generate() async {
    final lines = <String>['vorzela_native_splash — generating…'];
    final warnings = <String>[];

    if (config.android) {
      final android = AndroidWriter(root: root, config: config);
      await android.write(
        densify: _densifyPng,
        normalizeMaster: _normalizeMaster,
        warn: warnings.add,
      );
      lines.add('✓ Android (SplashScreen + mdpi→xxxhdpi, phones & tablets)');
    }

    if (config.ios) {
      final ios = IosWriter(root: root, config: config);
      await ios.write(
        densifyIos: _densifyIos,
        warn: warnings.add,
      );
      lines.add('✓ iOS (LaunchScreen + @1x/@2x/@3x, phone & iPad Auto Layout)');
    }

    await _writeGeneratedDartHint();
    lines.add('✓ Flutter handoff hint → lib/generated/vorzela_splash.g.dart');
    for (final w in warnings) {
      lines.add('⚠ $w');
    }
    lines.add('');
    lines.add('Dimensions (Android 12 / flutter_native_splash 2.4.x):');
    lines.add(
      '  icon no-bg  ${kAndroid12IconDp}dp → ${kAndroid12IconXxxhdpiPx}px @xxxhdpi',
    );
    lines.add(
      '  icon + bg   ${kAndroid12IconWithBgDp}dp → ${kAndroid12IconWithBgXxxhdpiPx}px @xxxhdpi',
    );
    lines.add(
      '  branding    $kBrandingWidthDp×$kBrandingHeightDp'
      'dp → $kBrandingXxxhdpiWidthPx×$kBrandingXxxhdpiHeightPx'
      'px @xxxhdpi',
    );
    lines.add(
      '  source PNG treated as @4x/xxxhdpi master (same as flutter_native_splash)',
    );
    lines.add('');
    lines.add('Next:');
    lines.add('  1. Wrap app with VorzelaSplashGate(animation: …)');
    lines.add('  2. Call VorzelaNativeSplash.preserve / remove as needed');
    lines.add('  3. flutter clean && flutter run');
    return GenerateResult(lines.join('\n'));
  }

  Future<void> _writeGeneratedDartHint() async {
    final dir = Directory(p.join(root, 'lib', 'generated'));
    if (!dir.existsSync()) dir.createSync(recursive: true);
    final anim = config.exitAnimation.name;
    final file = File(p.join(dir.path, 'vorzela_splash.g.dart'));
    await file.writeAsString('''
// GENERATED by vorzela_native_splash — do not edit by hand.
// ignore_for_file: constant_identifier_names

import 'package:vorzela_native_splash/vorzela_native_splash.dart';

const kVorzelaSplashColor = '${config.color}';
const kVorzelaSplashAnimationDurationMs = ${config.animationDurationMs};
const kVorzelaSplashExitAnimation = SplashExitAnimation.$anim;
''');
  }

  Future<img.Image> _loadImage(String sourcePath) async {
    final srcFile =
        File(p.isAbsolute(sourcePath) ? sourcePath : p.join(root, sourcePath));
    if (!srcFile.existsSync()) {
      throw StateError('Image not found: ${srcFile.path}');
    }
    final decoded = img.decodeImage(await srcFile.readAsBytes());
    if (decoded == null) {
      throw StateError('Could not decode image: ${srcFile.path}');
    }
    return decoded;
  }

  /// Fit [decoded] onto an official Android 12 canvas (xxxhdpi master).
  Future<img.Image> _normalizeMaster({
    required String sourcePath,
    required int masterWidthPx,
    required int masterHeightPx,
    void Function(String)? warn,
  }) async {
    final decoded = await _loadImage(sourcePath);
    if (decoded.width < masterWidthPx || decoded.height < masterHeightPx) {
      warn?.call(
        '$sourcePath is $decoded.width×$decoded.height; '
        'recommended master ≥ $masterWidthPx×$masterHeightPx'
        'px (@4x / xxxhdpi) for sharp tablets & xxxhdpi phones.',
      );
    }
    return img.copyResize(
      decoded,
      width: masterWidthPx,
      height: masterHeightPx,
      interpolation: img.Interpolation.average,
      maintainAspect: true,
      backgroundColor: img.ColorRgba8(0, 0, 0, 0),
    );
  }

  /// Densify like flutter_native_splash: source = @4x master, scale density/4.
  Future<void> _densifyPng({
    required String? sourcePath,
    required String outRoot,
    required String fileName,
    required int baseDp,
    Map<String, double>? folders,
    img.Image? master,
    int? masterWidthPx,
    int? masterHeightPx,
  }) async {
    if (sourcePath == null && master == null) return;

    late img.Image decoded;
    if (master != null) {
      decoded = master;
    } else if (masterWidthPx != null && masterHeightPx != null) {
      decoded = await _normalizeMaster(
        sourcePath: sourcePath!,
        masterWidthPx: masterWidthPx,
        masterHeightPx: masterHeightPx,
      );
    } else {
      decoded = await _loadImage(sourcePath!);
    }

    final map = folders ?? kAndroidDensities;
    for (final e in map.entries) {
      final w = (decoded.width * e.value / kMasterDensity).round().clamp(1, 8192);
      final h =
          (decoded.height * e.value / kMasterDensity).round().clamp(1, 8192);
      final resized = img.copyResize(
        decoded,
        width: w,
        height: h,
        interpolation: img.Interpolation.average,
      );
      final dir = Directory(p.join(outRoot, e.key));
      if (!dir.existsSync()) dir.createSync(recursive: true);
      await File(p.join(dir.path, fileName)).writeAsBytes(img.encodePng(resized));
    }
  }

  Future<void> _densifyIos({
    required String sourcePath,
    required String imagesetDir,
    required String baseName,
    void Function(String)? warn,
  }) async {
    final decoded = await _loadImage(sourcePath);
    if (decoded.width < 600 || decoded.height < 600) {
      warn?.call(
        'iOS $sourcePath is ${decoded.width}×${decoded.height}; '
        'prefer ≥ 1152×1152 (@4x) so @3x and iPad stay sharp.',
      );
    }

    final files = <String, int>{
      '$baseName.png': 1,
      '$baseName@2x.png': 2,
      '$baseName@3x.png': 3,
    };
    for (final e in files.entries) {
      final w = (decoded.width * e.value / kMasterDensity).round().clamp(1, 8192);
      final h =
          (decoded.height * e.value / kMasterDensity).round().clamp(1, 8192);
      final resized = img.copyResize(
        decoded,
        width: w,
        height: h,
        interpolation: img.Interpolation.average,
      );
      await File(p.join(imagesetDir, e.key)).writeAsBytes(img.encodePng(resized));
    }
  }

  static Future<String> remove(String root) async {
    final hint = File(p.join(root, 'lib', 'generated', 'vorzela_splash.g.dart'));
    if (hint.existsSync()) hint.deleteSync();
    return 'Removed generated Flutter splash hint. '
        'Native XML/storyboard edits are left in place — '
        'restore from git if you need a full rollback.';
  }
}
