import 'dart:io';

import 'package:image/image.dart' as img;
import 'package:path/path.dart' as p;

import 'android_writer.dart';
import 'config.dart';
import 'dimensions.dart';
import 'ios_writer.dart';

class GenerateResult {
  GenerateResult(this.summary);
  final String summary;
}

class SplashGenerator {
  SplashGenerator({required this.root, required this.config});

  final String root;
  final SplashConfig config;

  /// Cubic keeps hard logo edges; [Interpolation.average] softens/blurs marks.
  static const _sharp = img.Interpolation.cubic;

  Future<GenerateResult> generate() async {
    final lines = <String>['vorzela_native_splash — generating…'];
    final warnings = <String>[];

    if (config.android) {
      final android = AndroidWriter(root: root, config: config);
      await android.write(
        densify: _densifyPng,
        normalizeMaster: _normalizeMaster,
        warn: warnings.add,
      );
      lines.add('✓ Android (SplashScreen + mdpi→xxxhdpi, phones & tablets)');
    }

    if (config.ios) {
      final ios = IosWriter(root: root, config: config);
      await ios.write(
        densifyIos: _densifyIos,
        warn: warnings.add,
      );
      lines.add('✓ iOS (LaunchScreen + @1x/@2x/@3x, phone & iPad Auto Layout)');
    }

    await _writeGeneratedDartHint();
    lines.add('✓ Flutter handoff hint → lib/generated/vorzela_splash.g.dart');
    for (final w in warnings) {
      lines.add('⚠ $w');
    }
    lines.add('');
    lines.add('Sharpness: cubic resize, no soft upscale onto splash canvas.');
    lines.add(
      '  Prefer master PNG ≥ $kAndroid12IconXxxhdpiPx×$kAndroid12IconXxxhdpiPx'
      ' (or $kAndroid12IconWithBgXxxhdpiPx'
      'px with icon bg).',
    );
    lines.add('');
    lines.add('Next:');
    lines.add('  1. Wrap app with VorzelaSplashGate(animation: …)');
    lines.add('  2. Use SplashLogo.asset(…) or Image.filterQuality: high');
    lines.add('  3. flutter clean && flutter run');
    return GenerateResult(lines.join('\n'));
  }

  Future<void> _writeGeneratedDartHint() async {
    final dir = Directory(p.join(root, 'lib', 'generated'));
    if (!dir.existsSync()) dir.createSync(recursive: true);
    final anim = config.exitAnimation.name;
    final file = File(p.join(dir.path, 'vorzela_splash.g.dart'));
    await file.writeAsString('''
// GENERATED by vorzela_native_splash — do not edit by hand.
// ignore_for_file: constant_identifier_names

import 'package:vorzela_native_splash/vorzela_native_splash.dart';

const kVorzelaSplashColor = '${config.color}';
const kVorzelaSplashAnimationDurationMs = ${config.animationDurationMs};
const kVorzelaSplashExitAnimation = SplashExitAnimation.$anim;
''');
  }

  Future<img.Image> _loadImage(String sourcePath) async {
    final srcFile =
        File(p.isAbsolute(sourcePath) ? sourcePath : p.join(root, sourcePath));
    if (!srcFile.existsSync()) {
      throw StateError('Image not found: ${srcFile.path}');
    }
    final decoded = img.decodeImage(await srcFile.readAsBytes());
    if (decoded == null) {
      throw StateError('Could not decode image: ${srcFile.path}');
    }
    // Convert to RGBA so letterboxing stays crisp (no indexed-palette blur).
    return decoded.convert(numChannels: 4);
  }

  /// Fit onto official canvas **without soft upscaling**.
  ///
  /// Upscaling a small PNG onto 1152px is what makes splash logos look faint.
  /// We only downscale (cubic) when the source is larger; otherwise we center
  /// the original pixels on a transparent canvas.
  Future<img.Image> _normalizeMaster({
    required String sourcePath,
    required int masterWidthPx,
    required int masterHeightPx,
    void Function(String)? warn,
  }) async {
    final decoded = await _loadImage(sourcePath);
    if (decoded.width < masterWidthPx || decoded.height < masterHeightPx) {
      warn?.call(
        '$sourcePath is $decoded.width×$decoded.height — too small for a sharp '
        '$masterWidthPx×$masterHeightPx master. Provide a larger PNG '
        '(do not rely on upscaling). Centering original pixels instead.',
      );
    }

    img.Image fitted = decoded;
    if (decoded.width > masterWidthPx || decoded.height > masterHeightPx) {
      final scale = [
        masterWidthPx / decoded.width,
        masterHeightPx / decoded.height,
      ].reduce((a, b) => a < b ? a : b);
      fitted = img.copyResize(
        decoded,
        width: (decoded.width * scale).round().clamp(1, masterWidthPx),
        height: (decoded.height * scale).round().clamp(1, masterHeightPx),
        interpolation: _sharp,
      );
    }

    if (fitted.width == masterWidthPx && fitted.height == masterHeightPx) {
      return fitted;
    }

    final canvas = img.Image(
      width: masterWidthPx,
      height: masterHeightPx,
      numChannels: 4,
    );
    // Transparent canvas — composite original/downscaled pixels (no stretch).
    img.compositeImage(
      canvas,
      fitted,
      dstX: ((masterWidthPx - fitted.width) / 2).round(),
      dstY: ((masterHeightPx - fitted.height) / 2).round(),
    );
    return canvas;
  }

  /// Densify like flutter_native_splash: source = @4x master, scale density/4.
  Future<void> _densifyPng({
    required String? sourcePath,
    required String outRoot,
    required String fileName,
    required int baseDp,
    Map<String, double>? folders,
    img.Image? master,
    int? masterWidthPx,
    int? masterHeightPx,
  }) async {
    if (sourcePath == null && master == null) return;

    late img.Image decoded;
    if (master != null) {
      decoded = master;
    } else if (masterWidthPx != null && masterHeightPx != null) {
      decoded = await _normalizeMaster(
        sourcePath: sourcePath!,
        masterWidthPx: masterWidthPx,
        masterHeightPx: masterHeightPx,
      );
    } else {
      decoded = await _loadImage(sourcePath!);
    }

    final map = folders ?? kAndroidDensities;
    for (final e in map.entries) {
      final w = (decoded.width * e.value / kMasterDensity).round().clamp(1, 8192);
      final h =
          (decoded.height * e.value / kMasterDensity).round().clamp(1, 8192);
      final resized = _resizeSharp(decoded, w, h);
      final dir = Directory(p.join(outRoot, e.key));
      if (!dir.existsSync()) dir.createSync(recursive: true);
      await File(p.join(dir.path, fileName))
          .writeAsBytes(img.encodePng(resized, level: 6));
    }
  }

  Future<void> _densifyIos({
    required String sourcePath,
    required String imagesetDir,
    required String baseName,
    void Function(String)? warn,
  }) async {
    final decoded = await _loadImage(sourcePath);
    if (decoded.width < kAndroid12IconXxxhdpiPx ||
        decoded.height < kAndroid12IconXxxhdpiPx) {
      warn?.call(
        'iOS $sourcePath is $decoded.width×$decoded.height; '
        'prefer ≥ $kAndroid12IconXxxhdpiPx×$kAndroid12IconXxxhdpiPx (@4x) '
        'so @3x and iPad stay sharp (no soft upscale).',
      );
    }

    final files = <String, int>{
      '$baseName.png': 1,
      '$baseName@2x.png': 2,
      '$baseName@3x.png': 3,
    };
    for (final e in files.entries) {
      final w = (decoded.width * e.value / kMasterDensity).round().clamp(1, 8192);
      final h =
          (decoded.height * e.value / kMasterDensity).round().clamp(1, 8192);
      final resized = _resizeSharp(decoded, w, h);
      await File(p.join(imagesetDir, e.key))
          .writeAsBytes(img.encodePng(resized, level: 6));
    }
  }

  /// Skip no-op resizes; never soft-upscale density buckets.
  static img.Image _resizeSharp(img.Image src, int w, int h) {
    if (src.width == w && src.height == h) return src;
    if (w > src.width || h > src.height) {
      // Should not happen when source is a true @4x master; keep pixels sharp.
      final canvas = img.Image(width: w, height: h, numChannels: 4);
      img.compositeImage(
        canvas,
        src,
        dstX: ((w - src.width) / 2).round().clamp(0, w),
        dstY: ((h - src.height) / 2).round().clamp(0, h),
      );
      return canvas;
    }
    return img.copyResize(
      src,
      width: w,
      height: h,
      interpolation: _sharp,
    );
  }

  static Future<String> remove(String root) async {
    final hint = File(p.join(root, 'lib', 'generated', 'vorzela_splash.g.dart'));
    if (hint.existsSync()) hint.deleteSync();
    return 'Removed generated Flutter splash hint. '
        'Native XML/storyboard edits are left in place — '
        'restore from git if you need a full rollback.';
  }
}
