import 'dart:io';

import 'package:image/image.dart' as img;
import 'package:path/path.dart' as p;

import 'android_writer.dart';
import 'config.dart';
import 'ios_writer.dart';

class GenerateResult {
  GenerateResult(this.summary);
  final String summary;
}

class SplashGenerator {
  SplashGenerator({required this.root, required this.config});

  final String root;
  final SplashConfig config;

  static const androidDensities = <String, double>{
    'drawable-mdpi': 1,
    'drawable-hdpi': 1.5,
    'drawable-xhdpi': 2,
    'drawable-xxhdpi': 3,
    'drawable-xxxhdpi': 4,
  };

  /// Base size (mdpi) for splash logo — high source images are downscaled
  /// crisply into each bucket (up to 4× = xxxhdpi).
  static const baseLogoDp = 288;

  Future<GenerateResult> generate() async {
    final lines = <String>['vorzela_native_splash — generating…'];

    if (config.android) {
      final android = AndroidWriter(root: root, config: config);
      await android.write(
        densify: _densifyPng,
      );
      lines.add('✓ Android (SplashScreen + high-DPI drawables)');
    }

    if (config.ios) {
      final ios = IosWriter(root: root, config: config);
      await ios.write(densify: _densifyPng);
      lines.add('✓ iOS (LaunchScreen + @1x/@2x/@3x)');
    }

    await _writeGeneratedDartHint();
    lines.add('✓ Flutter handoff hint → lib/generated/vorzela_splash.g.dart');
    lines.add('');
    lines.add('Next:');
    lines.add('  1. Wrap app with VorzelaSplashGate(animation: …)');
    lines.add('  2. Call FlutterNativeSplash.preserve / remove as needed');
    lines.add('  3. flutter clean && flutter run');
    return GenerateResult(lines.join('\n'));
  }

  Future<void> _writeGeneratedDartHint() async {
    final dir = Directory(p.join(root, 'lib', 'generated'));
    if (!dir.existsSync()) dir.createSync(recursive: true);
    final anim = config.exitAnimation.name;
    final file = File(p.join(dir.path, 'vorzela_splash.g.dart'));
    await file.writeAsString('''
// GENERATED by vorzela_native_splash — do not edit by hand.
// ignore_for_file: constant_identifier_names

import 'package:vorzela_native_splash/vorzela_native_splash.dart';

const kVorzelaSplashColor = '${config.color}';
const kVorzelaSplashAnimationDurationMs = ${config.animationDurationMs};
const kVorzelaSplashExitAnimation = SplashExitAnimation.$anim;
''');
  }

  /// Resize [sourcePath] into density buckets under [outRoot]/[folder]/[fileName].
  Future<void> _densifyPng({
    required String? sourcePath,
    required String outRoot,
    required String fileName,
    required int baseDp,
    Map<String, double>? folders,
  }) async {
    if (sourcePath == null) return;
    final srcFile = File(p.isAbsolute(sourcePath) ? sourcePath : p.join(root, sourcePath));
    if (!srcFile.existsSync()) {
      throw StateError('Image not found: ${srcFile.path}');
    }
    final bytes = await srcFile.readAsBytes();
    final decoded = img.decodeImage(bytes);
    if (decoded == null) {
      throw StateError('Could not decode image: ${srcFile.path}');
    }

    final map = folders ?? androidDensities;
    for (final e in map.entries) {
      final px = (baseDp * e.value).round();
      final resized = img.copyResize(
        decoded,
        width: px,
        height: px,
        interpolation: img.Interpolation.cubic,
      );
      final dir = Directory(p.join(outRoot, e.key));
      if (!dir.existsSync()) dir.createSync(recursive: true);
      final out = File(p.join(dir.path, fileName));
      await out.writeAsBytes(img.encodePng(resized));
    }
  }

  static Future<String> remove(String root) async {
    final hint = File(p.join(root, 'lib', 'generated', 'vorzela_splash.g.dart'));
    if (hint.existsSync()) hint.deleteSync();
    return 'Removed generated Flutter splash hint. '
        'Native XML/storyboard edits are left in place — '
        'restore from git if you need a full rollback.';
  }
}
